### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Infinality** [bgstack15/certreq#1]
This script is a lifesaver.  I couldn't imagine having to do hundreds of these manually.  With that said, I'd like to request a feature:  We recently locked down our PKI so that it requires a security person to manually "Issue" each certificate.  This script is currently designed to assume that certificates are automatically issued, but could the certificate creation/request and certificate fetching/processing be turned into two separate actions with command line parameters?  Perhaps it could use the "ReqId" (Request ID) that certserv provides when the certificate is requested as a parameter to pass when fetching?

**Comment by bgstack15** [comment]
Unfortunately without the same-configured certsrv behavior, I won't be able to retrieve sample web pages to extract the request ID and then the field to upload it to in the web calls. I don't have a test PKI environment, only prod. Please submit a pull request with your improvements if you upgrade it yourself! I used Firefox with developer tools (F12) and inspected the traffic and source (^U).

**Comment by Infinality** [comment]
Ok, I implemented the feature and have pasted the updated script here:  https://pastebin.com/pPshXvqT

The idea is that all existing flags still work, but new flags were added to do specific fetching / requesting.  I've lightly tested it with a PKI that requires manual certificate issuing, but haven't tested it with automatic issuing.  So, you might want to try that on your end.

**Comment by bgstack15** [comment]
Thanks for your submission! When I get time, I'll add your contributions into the new format. I rewrote the script to use functions, so hopefully it'll be easy to just add some new functions for the individual components you have provided, and new actions with the requisite workflows.

**Comment by bgstack15** [comment]
I forgot to magically link the commit to this issue, but please check out https://github.com/bgstack15/certreq/commit/0c13efd9374b36594852bed082652f803c2cd7a2 and see if it works with your use case.
